### ISSUE TITLE
Alerts should support internationalisation

### ISSUE THREAD

**Issue by MichaelMarner** [NextFaze/ionic-manup#1]
Alert text is currently hardcoded English. Should support internationalisation

**Comment by chawax** [comment]
Agree with that. A simple way to do this would be to add properties in the ManupConfig class, the same it has been well done for "url" property.

**Comment by zbarbuto** [comment]
Definitely add to config file. Allows leaving a specific message for maintenance mode such as including downtime duration information.

**Comment by nextalias** [comment]
I am concerned the config file will get too bloated with translations; suggest allowing language files to be externalised in different files to keep config file lean.

**Comment by zbarbuto** [comment]
It doesn't have to have a bunch of translations. It should at least support setting the message remotely and possibly doing so using a machine readable code that could be used for client side translation e.g `'WEEKLY_SERVER_MAINTENANCE'`

This sort of leads to a second issue which would be allowing custom handlers for the different man up events so you could capture the maintenance code and translate/render it how you wish (show splash, exit app, etc).

**Comment by MichaelMarner** [comment]
I would add an optional `eta` timestamp to the config. That way you can rely on moment to present the time and use regular ionic/angular translation mechanisms

**Comment by MichaelMarner** [comment]
PR #12 added support for internationalisation. However, as a naive isolated Australian, the only languages currently supported are English, and a Google Translate attempt at Spanish.

I'm closing this issue, but please consider making a PR if you are able to translate ManUp into another language :)

(hint hint @yanglongli)
