### ISSUE TITLE
Keep pace with ionic-native 3

### ISSUE THREAD

**Issue by MichaelMarner** [NextFaze/ionic-manup#13]
As per this comment:

https://github.com/NextFaze/ionic-manup/issues/9#issuecomment-285919939

Ionic plans on dividing up Ionic Native with version 3. ManUp should only require the bits it actually needs to work.

**Comment by yanglongji** [comment]
yes.
I've upgraded to ionic3. AND there're lots of errors.
I can't go on now......   /(ㄒoㄒ)/~~
waiting for updating~~~~~   (☆▽☆)

**Comment by yanglongji** [comment]
and also ionic3 uses ngx-translate
