### ISSUE TITLE
Allow action if error to be configurable

### ISSUE THREAD

**Issue by MichaelMarner** [NextFaze/ionic-manup#26]
Currently ManUp.validate resolves if any error occurs, allowing the user to use the app if, for example, the version metadata could not be fetched.

This behaviour should be configurable, to allow the app developer to decide what to do if metadata evaluation could not happen

**Comment by TheMadBug** [comment]
In the scenario of the metadata not being read - a likely desired outcome would be:

Warn the user that the server is down for maintenance. (Especially handy if you've decided to host/generate the manup.json in your API server).

Possibly raise an error with whatever my error reporting tool of choice is (rollbar, etc). So I'd still want the calling code to know there was an error. Actually even when manup is working 100% as advertised it would be handy to know that .validate() failed for logging purposes. Will give me an idea of how many people run up incompatible versions.

**Comment by zbarbuto** [comment]
New feature to be released in 2.0.0
