### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yanglongji** [NextFaze/ionic-manup#28]
return this.presentAlert(result, metadata); 
should be 
return this.presentAlert(result, this.getPlatformData(metadata));

**Comment by yanglongji** [comment]
actually, should be :
return this.presentAlert(result, this.getPlatformData(metadata)).then(()=>{
resolve()
});
because the resolve used in alert() not the resolve in here, so if the alert return resolve(), here should also return resolve()

**Comment by MichaelMarner** [comment]
Thanks for reporting this issue. I should be able to have a fix out by Friday, but PRs are welcome if you want to have a look :)
