### ISSUE TITLE
HTTP Loaded translations with externalTranslations: false cause built in translations to be ignored

### ISSUE THREAD

**Issue by zbarbuto** [NextFaze/ionic-manup#31]
Using 

```typescript
        ManUpModule.forRoot({
          url: 'https://example.com/manup.json',
          externalTranslations: false
        }),
```

in conjunction with an injected translate service causes the translate service to still be used, even though `externalTranslations` is explicitly false.

**Comment by MichaelMarner** [comment]
ManUpService will _always_ use the translate service if it is injected in. However, if externalTranslations is false the service will add it's own translation strings.

**Comment by MichaelMarner** [comment]
translateModule.forFeature allows modules to add a missing translation handler, might be a better way of dealing with translations than having the service add them when it is initialised

**Comment by zbarbuto** [comment]
Updated title to be indicative of the issue at hand.
