### ISSUE TITLE
Update button not working

### ISSUE THREAD

**Issue by niyaswebtree** [NextFaze/ionic-manup#34]
When i clicking on Update button, nothing happening. While 'Not now' button is working fine. I followed all  the integration things perfectly. Please help me out.

**Comment by MichaelMarner** [comment]
do you get any errors printed to the console? What URL do you have set for the update link? What platforms (ios, android, both?)

**Comment by niyaswebtree** [comment]
> do you get any errors printed to the console? What URL do you have set for the update link? What platforms (ios, android, both?)

For both Android and iOS. The json is like 
{
  "ios": {
    "latest": "1.2.3",
    "minimum": "1.2.2",
    "url": "http://example.com/myAppUpdate",
    "enabled": true
  },
  "android": {
    "latest": "1.2.3",
    "minimum": "1.2.1",
    "url": "https://play.google.com/store/apps/details?id=com.webtree.salonkom",
    "enabled": true
  }
}

Am getting nothing on the console. How i get console logs on manup.validate()

**Comment by niyaswebtree** [comment]
Hi There any updates on the same?

**Comment by MichaelMarner** [comment]
Does the demo app work for you?

**Comment by niyaswebtree** [comment]
yes..demo app is working with the same json file

**Comment by niyaswebtree** [comment]
I did all things same like demo app. but still not working my application. please help me out
