### ISSUE TITLE
Set max alert frequency for optional update

### ISSUE THREAD

**Issue by MichaelMarner** [NextFaze/ionic-manup#8]
Add a configurable delay between notifying the user of an optional update.

Currently, an optional update alert is presented every time the user opens the app, if an optional update is available. This could be fairly annoying for users.

Suggest adding a delay to the Manup configuration:

```ts
ManUpModule.forRoot({
  url: 'https://example.com/manup.json', 
  optionalAlertFrequency: '1d'
})
```

The frequency could be specified either as number of seconds, a `moment` duration object, or a string, as above. Any would work.

**Comment by sreekanth-karini** [comment]
I want this enhancement is this fixed or available plz tell me.. how to do this..?

**Comment by MichaelMarner** [comment]
Hi. No this has not been implemented yet. PRs are welcome if you want to try yourself :)

**Comment by zbarbuto** [comment]
Support for this is not likely to be added but feel free to submit a pull request if it's something you would like.
