### ISSUE TITLE
ionic-manup/index"' has no exported member 'ManUpService'

### ISSUE THREAD

**Issue by yanglongji** [NextFaze/ionic-manup#9]
what's the problem？

**Comment by MichaelMarner** [comment]
Hi

Thanks for the bug report, sorry I missed this problem in 0.0.5. I have fixed this problem on `master` and will incorporate it into a new release on npm tomorrow.

Cheers
Michael

**Comment by yanglongji** [comment]
thx. And does manup have any configs or methods to set the tip words. I'm from china. so, you know....

**Comment by MichaelMarner** [comment]
Internationalisation support is on the list (#1).

**Comment by yanglongji** [comment]
too complex
prefer to modify the text in manup file  :-D

**Comment by yanglongji** [comment]
i'm facing another issue now :-D
check this out http://blog.ionic.io/help-us-test-ionic-native-3-x/
when i used ionic2 like this & manup, then I got the error of "can't find module 'ionic-native'", cause the manup uses 'ionic-native'.....
hope to see next edition soon.
thanks for the awesome plugin for ionic2

**Comment by MichaelMarner** [comment]
Please file a new issue, as this one is closed.

Thanks
